import Bitcoin from "../assets/bitcoin.svg";
import Ethereum from "../assets/ethereum.svg";
import Tether from "../assets/tether.svg";

export const state = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT - Abuja",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
];

export const cryptos = [
  {
    id: 2,
    name: "Bitcoin",
    img: Bitcoin,
    classname: "accounts_img accounts_img-2",
    slug: "bitcoin",
    rate: "BTC",
    symbol: "BTC",
    type: "BTC",
  },
  {
    id: 3,
    name: "Ethereum",
    img: Ethereum,
    classname: "accounts_img accounts_img-3",
    slug: "ethereum",
    rate: "ETH",
    symbol: "ETH",
    type: "ETH",
  },
  {
    id: 4,
    name: "USDT (ERC20)",
    img: Tether,
    classname: "accounts_img accounts_img-4",
    slug: "usdt-eth",
    rate: "USDT",
    symbol: "USDT_ETH",
    type: "USDT_ETH",
  },
  {
    id: 5,
    name: "USDT (TRC20)",
    img: Tether,
    classname: "accounts_img accounts_img-4",
    slug: "usdt-trx",
    rate: "USDT",
    symbol: "USDT_TRC20",
    type: "USDT_TRX",
  },
];
